回归问题：使用movielens数据集中的特征预测该用户给目标电影的评分评分（ratings）：

* 用户观看电影序列 sequence of movie_id（固定长度）。
* 用户对其观看过的电影的评分序列 sequence of ratings。
* 用户画像：`user_id`，`sex`，`occupation` 和 `age_group`。
* 输入序列中每部电影和目标电影的 `类型（genres）` 。
* 预测目标 target_movie_id 的ratings。

修改方式：
* 我们将电影特征（类型）合并到输入序列的每个电影和目标电影的嵌入处理中，而不是将它们视为transformer外部的“other_feature”。
* 我们利用输入序列中的电影评分以及它们在序列中的位置来更新电影，然后再将它们输入到self-attention中。

# 加载数据

In [34]:
! wget http://files.grouplens.org/datasets/movielens/ml-1m.zip
! unzip -o ml-1m.zip

--2021-04-14 02:04:32--  http://files.grouplens.org/datasets/movielens/ml-1m.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5917549 (5.6M) [application/zip]
Saving to: ‘ml-1m.zip.1’

ml-1m.zip.1         100%[===================>]   5.64M  26.3MB/s    in 0.2s

2021-04-14 02:04:33 (26.3 MB/s) - ‘ml-1m.zip.1’ saved [5917549/5917549]

Archive:  ml-1m.zip
  inflating: ml-1m/movies.dat
  inflating: ml-1m/ratings.dat
  inflating: ml-1m/README
  inflating: ml-1m/users.dat

In [35]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [36]:
users = pd.read_csv('./ml-1m/users.dat', sep='::', names=['user_id', 'sex', 'age_group', 'occupation','zip_code'])
ratings = pd.read_csv('./ml-1m/ratings.dat', sep='::', names=['user_id', 'movie_id', 'rating', 'unix_timestamp'])
movies = pd.read_csv('./ml-1m/movies.dat', sep="::", names=['movie_id', 'title', 'genres'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

In [37]:
users.head(1)

   user_id sex  age_group  occupation zip_code
0        1   F          1          10    48067

In [38]:
ratings.head(1)

   user_id  movie_id  rating  unix_timestamp
0        1      1193       5       978300760

In [39]:
movies.head(1)

   movie_id             title                       genres
0         1  Toy Story (1995)  Animation|Children's|Comedy

In [40]:
# 合并为一个大DataFrame
matrix = pd.merge(users, ratings, on='user_id', how='left')
matrix = pd.merge(matrix, movies, on='movie_id', how='left')

# 性别特征做0-1编码
temp = pd.get_dummies(matrix['sex'], prefix = 'sex')
matrix = pd.concat([matrix, temp], axis=1)
matrix.drop('sex', axis=1, inplace=True)

In [41]:
# gender_genres = genres
# gender_genres.append('sex_F')
# gender_genres.append('sex_M')
# matrix[genres + str('sex_F') + str('sex+M')]#.head(1)

## 特征工程

### 单标签编码：movie_id、age_group、rating、occupation

In [42]:
# from sklearn.preprocessing import LabelEncoder
# for i in ['user_id', 'age_group', 'occupation']:
#     users[i] = LabelEncoder().fit_transform(users[i])

# for i in ['movie_id', 'user_id', 'rating']:
#     ratings[i] = LabelEncoder().fit_transform(ratings[i])

# movies['movie_id'] = LabelEncoder().fit_transform(movies['movie_id'])

In [43]:
users["user_id"] = users["user_id"].apply(lambda x: f"user_{x}")
users["age_group"] = users["age_group"].apply(lambda x: f"group_{x}")
users["occupation"] = users["occupation"].apply(lambda x: f"occupation_{x}")

movies["movie_id"] = movies["movie_id"].apply(lambda x: f"movie_{x}")

ratings["movie_id"] = ratings["movie_id"].apply(lambda x: f"movie_{x}")
ratings["user_id"] = ratings["user_id"].apply(lambda x: f"user_{x}")
ratings["rating"] = ratings["rating"].apply(lambda x: float(x))

这里不使用LabelEncoder，否则后面再处理 DataFrame中list变为 str 会出错

In [44]:
users.head(1)

  user_id sex age_group     occupation zip_code
0  user_1   F   group_1  occupation_10    48067

In [45]:
movies.head(1)

  movie_id             title                       genres
0  movie_1  Toy Story (1995)  Animation|Children's|Comedy

In [46]:
ratings.head(1)

  user_id    movie_id  rating  unix_timestamp
0  user_1  movie_1193     5.0       978300760

### 多标签编码：电影类型 genres

In [47]:
genres = ["Action","Adventure", "Animation", "Children's", "Comedy", "Crime",
    "Documentary","Drama","Fantasy", "Film-Noir", "Horror", "Musical","Mystery",
    "Romance","Sci-Fi","Thriller","War","Western"]

for genre in genres: 
    movies[genre] = movies['genres'].apply(lambda x: int(genre in x.split('|')))

In [48]:
movies.head(1)

  movie_id             title  ... War  Western
0  movie_1  Toy Story (1995)  ...   0        0

[1 rows x 21 columns]

### 特征序列化：电影评分转换为序列

* 我们按照时间（unix_timestamp）对评分进行排序，再将 movie_id 和 ratings 按 user_id分组（groupby)。

* 输出DataFrame是每个user_id已评分电影的序列 和 这些电影的评分。

In [49]:
ratings_group = ratings.sort_values(by=["unix_timestamp"]).groupby("user_id")

ratings_data = pd.DataFrame({"user_id": list(ratings_group.groups.keys()),
                            "movie_ids": list(ratings_group.movie_id.apply(list)),
                            "ratings": list(ratings_group.rating.apply(list)),
                            "timestamps": list(ratings_group.unix_timestamp.apply(list)),}
)

In [50]:
ratings_data.head(2)

   user_id  ...                                         timestamps
0   user_1  ...  [978300019, 978300055, 978300055, 978300055, 9...
1  user_10  ...  [978224375, 978224375, 978224375, 978224400, 9...

[2 rows x 4 columns]

### 构建数据集：用户看过电影id每4个做一组，用户评分每4个做一组

* 将 `movie_ids` 列表分成一组固定长度的序列，`ratings`也是如此。 设置`sequence_length` 变量就可以更改输入序列的长度；更改`step_size`以控制要为每个用户生成的sequences。

* 业务场景说明序列越靠近现今价值越大，所以我们选择用户点击序列的倒数前4个。阿里巴巴DIEN中是使用最近200个序列固定序列长度，这种方法也让重度电影爱好者和轻度电影爱好者具有相同的权重，预测过程中模型能对 重度使用者 和 轻度使用使用者一视同仁。

In [51]:
# movie_ids[-sequence_length: ] # 最近200个用户点击行为的价值更大
sequence_length = 4
step_size = 2

def create_sequences(values, window_size, step_size):
    sequences = []
    start_index = 0
    while True:
        end_index = start_index + window_size
        seq = values[start_index:end_index]
        if len(seq) < window_size:
            seq = values[-window_size:]
            if len(seq) == window_size:
                sequences.append(seq)
            break
        sequences.append(seq)
        start_index += step_size
    return sequences


ratings_data.movie_ids = ratings_data.movie_ids.apply(
    lambda ids: create_sequences(ids, sequence_length, step_size)
)

ratings_data.ratings = ratings_data.ratings.apply(
    lambda ids: create_sequences(ids, sequence_length, step_size)
)

del ratings_data["timestamps"]

In [52]:
# 每个用户看过电影序列的序列 和 看过电影的评分序列
ratings_data.head(2)

   user_id  ...                                            ratings
0   user_1  ...  [[4.0, 4.0, 5.0, 5.0], [5.0, 5.0, 3.0, 5.0], [...
1  user_10  ...  [[4.0, 3.0, 3.0, 4.0], [3.0, 4.0, 4.0, 5.0], [...

[2 rows x 3 columns]

让每个序列在DataFrame中独立成行。 

将user feature与ratings数据结合在一起。

In [53]:
ratings_data_movies = ratings_data[["user_id", "movie_ids"]].explode(
    "movie_ids", ignore_index=True
)
ratings_data_rating = ratings_data[["ratings"]].explode("ratings", ignore_index=True)
ratings_data_transformed = pd.concat([ratings_data_movies, ratings_data_rating], axis=1)
ratings_data_transformed = ratings_data_transformed.join(
    users.set_index("user_id"), on="user_id"
)

In [54]:
ratings_data_movies.head(3)

  user_id                                         movie_ids
0  user_1  [movie_3186, movie_1721, movie_1270, movie_1022]
1  user_1  [movie_1270, movie_1022, movie_2340, movie_1836]
2  user_1  [movie_2340, movie_1836, movie_3408, movie_1207]

In [55]:
# pandas中的 list --> str : [4.0, 4.0, 5.0, 5.0]  --> 4.0, 4.0, 5.0, 5.0

ratings_data_transformed.movie_ids = ratings_data_transformed.movie_ids.apply(
    lambda x: ",".join(x)
)
ratings_data_transformed.ratings = ratings_data_transformed.ratings.apply(
    lambda x: ",".join([str(v) for v in x])
)

del ratings_data_transformed["zip_code"]

ratings_data_transformed.rename(
    columns={"movie_ids": "sequence_movie_ids", "ratings": "sequence_ratings"},
    inplace=True,
)

In [56]:
ratings_data_transformed.head(2)

  user_id                           sequence_movie_ids  ... age_group     occupation
0  user_1  movie_3186,movie_1721,movie_1270,movie_1022  ...   group_1  occupation_10
1  user_1  movie_1270,movie_1022,movie_2340,movie_1836  ...   group_1  occupation_10

[2 rows x 6 columns]

在sequence_length=4且 step_size=2的情况下，我们得到498,623个序列。

85％数据作为训练集， 15％的数据作为测试集

In [57]:
random_selection = np.random.rand(len(ratings_data_transformed.index)) <= 0.85
train_data = ratings_data_transformed[random_selection]
test_data = ratings_data_transformed[~random_selection]

train_data.to_csv("train_data.csv", index=False, sep="|", header=False)
test_data.to_csv("test_data.csv", index=False, sep="|", header=False)

In [58]:
# matrix = users.merge(ratings, on='user_id', how='left')
# matrix = matrix.merge(movies, on='movie_id', how='left')

In [59]:
# matrix.head(2)

In [60]:
# 特征工程
# matrix['sex']= pd.get_dummies(matrix['sex'], prefix_sex='sex')
# from sklearn.preprocessing import LabelEncoder
# matrix['sex'] = LabelEncoder().fit_transform(matrix['sex'])

## 定义数据

In [62]:
CSV_HEADER = list(ratings_data_transformed.columns)

CATEGORICAL_FEATURES_WITH_VOCABULARY = {
    "user_id": list(users.user_id.unique()),
    "movie_id": list(movies.movie_id.unique()),
    "sex": list(users.sex.unique()),
    "age_group": list(users.age_group.unique()),
    "occupation": list(users.occupation.unique()),
}

# 用户画像
USER_FEATURES = ["sex", "age_group", "occupation"]

# 电影画像
MOVIE_FEATURES = ["genres"]

## 通过`tf.data.Dataset`创建训练集(training)和测试集(evaluation)

In [63]:
def get_dataset_from_csv(csv_file_path, shuffle=False, batch_size=128):
    def process(features):
        movie_ids_string = features["sequence_movie_ids"]
        sequence_movie_ids = tf.strings.split(movie_ids_string, ",").to_tensor()

        # 预测目标是用户观看电影序列的最后一部电影：The last movie id in the sequence is the target movie.
        features["target_movie_id"] = sequence_movie_ids[:, -1]
        features["sequence_movie_ids"] = sequence_movie_ids[:, :-1]

        ratings_string = features["sequence_ratings"]
        sequence_ratings = tf.strings.to_number(
            tf.strings.split(ratings_string, ","), tf.dtypes.float32
        ).to_tensor()

        # 用户观看电影评分序列的最后一部电影作为评分预测的目标：The last rating in the sequence is the target for the model to predict.
        target = sequence_ratings[:, -1]
        features["sequence_ratings"] = sequence_ratings[:, :-1]
        return features, target

    dataset = tf.data.experimental.make_csv_dataset(
        csv_file_path,
        batch_size=batch_size,
        column_names=CSV_HEADER,
        num_epochs=1,
        header=False,
        field_delim="|",
        shuffle=shuffle,
    ).map(process)

    return dataset

In [64]:
# 测试
train_test= get_dataset_from_csv('train_data.csv', shuffle=True, batch_size=265)

In [65]:
# 显示第一条喂给模型的数据
next(iter(train_test))

(OrderedDict([('user_id', <tf.Tensor: shape=(265,), dtype=string, numpy=
               array([b'user_1000', b'user_1040', b'user_1100', b'user_1069',
                      b'user_1110', b'user_1101', b'user_1015', b'user_1015',
                      b'user_1031', b'user_1082', b'user_1010', b'user_1115',
                      b'user_1117', b'user_1020', b'user_1019', b'user_1029',
                      b'user_1029', b'user_1015', b'user_1017', b'user_1082',
                      b'user_1086', b'user_1109', b'user_1101', b'user_1015',
                      b'user_1117', b'user_1068', b'user_1001', b'user_1017',
                      b'user_1112', b'user_1017', b'user_1015', b'user_1100',
                      b'user_1088', b'user_10', b'user_1034', b'user_1067', b'user_1042',
                      b'user_1100', b'user_1112', b'user_1037', b'user_1084',
                      b'user_1001', b'user_1019', b'user_1032', b'user_100',
                      b'user_1050', b'user_1086', b'user_1004', b'user_1072',
                      b'user_1016', b'user_1088', b'user_1004', b'user_1015',
                      b'user_1069', b'user_1068', b'user_1106', b'user_1059',
                      b'user_1034', b'user_1112', b'user_1088', b'user_1044',
                      b'user_1068', b'user_1032', b'user_1050', b'user_1034',
                      b'user_1001', b'user_1058', b'user_1090', b'user_1113',
                      b'user_1015', b'user_1084', b'user_1059', b'user_1053',
                      b'user_1077', b'user_1004', b'user_105', b'user_1087',
                      b'user_1068', b'user_1072', b'user_1015', b'user_1028',
                      b'user_1010', b'user_1086', b'user_1010', b'user_1100',
                      b'user_1004', b'user_10', b'user_1101', b'user_101', b'user_1069',
                      b'user_1043', b'user_1096', b'user_10', b'user_1004', b'user_1033',
                      b'user_1086', b'user_1084', b'user_1051', b'user_1047',
                      b'user_1051', b'user_1113', b'user_1058', b'user_1029',
                      b'user_1068', b'user_1068', b'user_1069', b'user_1063',
                      b'user_1068', b'user_1117', b'user_1015', b'user_1033',
                      b'user_1040', b'user_1017', b'user_1017', b'user_1104',
                      b'user_1020', b'user_1015', b'user_1088', b'user_1032',
                      b'user_1112', b'user_1097', b'user_1117', b'user_1050',
                      b'user_1068', b'user_1015', b'user_1000', b'user_1087',
                      b'user_1019', b'user_1014', b'user_1059', b'user_1113',
                      b'user_1030', b'user_1113', b'user_1073', b'user_1068',
                      b'user_1059', b'user_1059', b'user_1036', b'user_1024',
                      b'user_1040', b'user_1101', b'user_1019', b'user_1031',
                      b'user_1063', b'user_1068', b'user_1115', b'user_1017',
                      b'user_1013', b'user_1110', b'user_1051', b'user_1096',
                      b'user_1059', b'user_1017', b'user_1015', b'user_1077',
                      b'user_1050', b'user_1100', b'user_1024', b'user_1088',
                      b'user_1018', b'user_1105', b'user_1058', b'user_1100',
                      b'user_1019', b'user_1004', b'user_1015', b'user_1077',
                      b'user_1016', b'user_1068', b'user_1115', b'user_1101',
                      b'user_1050', b'user_1058', b'user_1019', b'user_1096',
                      b'user_1081', b'user_1067', b'user_1033', b'user_1019',
                      b'user_1088', b'user_1010', b'user_1051', b'user_1051',
                      b'user_1040', b'user_1010', b'user_1088', b'user_1110',
                      b'user_1069', b'user_1088', b'user_1117', b'user_1031',
                      b'user_1051', b'user_1050', b'user_1033', b'user_1054',
                      b'user_1041', b'user_1019', b'user_1010', b'user_103',
                      b'user_1069', b'user_1035', b'user_1051', b'user_1051',
                      b'user_1066', b'user_1094', b'user_1088', b'user_1001',
                      b'user_1051', b'user_1050', b'user_1076', b'user_1100',
                      b'user_1010', b'user_1022', b'user_1100', b'user_1068',
                      b'user_1057', b'user_1080', b'user_1096', b'user_1010',
                      b'user_1008', b'user_1086', b'user_1068', b'user_1117',
                      b'user_100', b'user_1034', b'user_1001', b'user_1112',
                      b'user_1103', b'user_1019', b'user_109', b'user_105', b'user_1055',
                      b'user_1063', b'user_1015', b'user_1010', b'user_1051',
                      b'user_1041', b'user_1053', b'user_1011', b'user_1112',
                      b'user_1019', b'user_1068', b'user_1030', b'user_1034',
                      b'user_1017', b'user_1053', b'user_1057', b'user_1001',
                      b'user_1051', b'user_1015', b'user_1042', b'user_1087',
                      b'user_1054', b'user_1004', b'user_1119', b'user_1019',
                      b'user_1106', b'user_1058', b'user_1053', b'user_1042',
                      b'user_1010', b'user_11', b'user_1090', b'user_1053', b'user_1086'],
                     dtype=object)>),
              ('sequence_movie_ids',
               <tf.Tensor: shape=(265, 3), dtype=string, numpy=
               array([[b'movie_2990', b'movie_2973', b'movie_1210'],
                      [b'movie_1213', b'movie_608', b'movie_50'],
                      [b'movie_357', b'movie_449', b'movie_1966'],
                      [b'movie_196', b'movie_435', b'movie_1882'],
                      [b'movie_3179', b'movie_2858', b'movie_2707'],
                      [b'movie_3735', b'movie_1278', b'movie_1263'],
                      [b'movie_1249', b'movie_335', b'movie_2186'],
                      [b'movie_2542', b'movie_3260', b'movie_1639'],
                      [b'movie_380', b'movie_2476', b'movie_1101'],
                      [b'movie_2529', b'movie_2455', b'movie_2021'],
                      [b'movie_2264', b'movie_3387', b'movie_2717'],
                      [b'movie_593', b'movie_3362', b'movie_608'],
                      [b'movie_2395', b'movie_1610', b'movie_475'],
                      [b'movie_2334', b'movie_3107', b'movie_1608'],
                      [b'movie_592', b'movie_1283', b'movie_1266'],
                      [b'movie_2301', b'movie_2518', b'movie_2141'],
                      [b'movie_3399', b'movie_2413', b'movie_1378'],
                      [b'movie_1231', b'movie_971', b'movie_2927'],
                      [b'movie_2011', b'movie_3061', b'movie_2362'],
                      [b'movie_34', b'movie_1271', b'movie_531'],
                      [b'movie_2194', b'movie_2366', b'movie_3753'],
                      [b'movie_969', b'movie_1210', b'movie_303'],
                      [b'movie_1573', b'movie_2011', b'movie_1320'],
                      [b'movie_2843', b'movie_2961', b'movie_386'],
                      [b'movie_2700', b'movie_3006', b'movie_2959'],
                      [b'movie_2134', b'movie_2424', b'movie_2145'],
                      [b'movie_2692', b'movie_608', b'movie_1354'],
                      [b'movie_1975', b'movie_2652', b'movie_2122'],
                      [b'movie_364', b'movie_2081', b'movie_2746'],
                      [b'movie_3459', b'movie_2149', b'movie_2868'],
                      [b'movie_2700', b'movie_898', b'movie_2396'],
                      [b'movie_1665', b'movie_1091', b'movie_2002'],
                      [b'movie_2763', b'movie_1377', b'movie_1616'],
                      [b'movie_2872', b'movie_3095', b'movie_3198'],
                      [b'movie_674', b'movie_2605', b'movie_2431'],
                      [b'movie_924', b'movie_3503', b'movie_1219'],
                      [b'movie_3446', b'movie_364', b'movie_2662'],
                      [b'movie_2', b'movie_1019', b'movie_1007'],
                      [b'movie_2006', b'movie_1391', b'movie_1028'],
                      [b'movie_818', b'movie_2412', b'movie_2004'],
                      [b'movie_1', b'movie_2700', b'movie_1923'],
                      [b'movie_2395', b'movie_2336', b'movie_2359'],
                      [b'movie_1946', b'movie_2243', b'movie_2067'],
                      [b'movie_2', b'movie_2297', b'movie_1665'],
                      [b'movie_1580', b'movie_3107', b'movie_380'],
                      [b'movie_2353', b'movie_377', b'movie_1488'],
                      [b'movie_1385', b'movie_288', b'movie_2490'],
                      [b'movie_2089', b'movie_1032', b'movie_3213'],
                      [b'movie_1196', b'movie_2160', b'movie_527'],
                      [b'movie_339', b'movie_2424', b'movie_1356'],
                      [b'movie_1270', b'movie_2863', b'movie_3341'],
                      [b'movie_1375', b'movie_3444', b'movie_303'],
                      [b'movie_1346', b'movie_1327', b'movie_3708'],
                      [b'movie_2025', b'movie_2252', b'movie_481'],
                      [b'movie_2087', b'movie_2078', b'movie_2310'],
                      [b'movie_524', b'movie_661', b'movie_366'],
                      [b'movie_2678', b'movie_1816', b'movie_3707'],
                      [b'movie_2709', b'movie_2048', b'movie_2123'],
                      [b'movie_1676', b'movie_2432', b'movie_2841'],
                      [b'movie_2081', b'movie_1032', b'movie_1366'],
                      [b'movie_2352', b'movie_1962', b'movie_921'],
                      [b'movie_1377', b'movie_57', b'movie_147'],
                      [b'movie_1883', b'movie_2907', b'movie_3418'],
                      [b'movie_432', b'movie_725', b'movie_3031'],
                      [b'movie_2043', b'movie_3204', b'movie_2294'],
                      [b'movie_457', b'movie_1358', b'movie_2610'],
                      [b'movie_3755', b'movie_3827', b'movie_3555'],
                      [b'movie_954', b'movie_924', b'movie_1246'],
                      [b'movie_1562', b'movie_2389', b'movie_2124'],
                      [b'movie_206', b'movie_1036', b'movie_2947'],
                      [b'movie_3948', b'movie_3624', b'movie_3578'],
                      [b'movie_318', b'movie_2289', b'movie_36'],
                      [b'movie_931', b'movie_3476', b'movie_2467'],
                      [b'movie_2712', b'movie_1982', b'movie_2716'],
                      [b'movie_2139', b'movie_2700', b'movie_2096'],
                      [b'movie_1221', b'movie_1387', b'movie_2028'],
                      [b'movie_2324', b'movie_2321', b'movie_2997'],
                      [b'movie_2875', b'movie_1363', b'movie_2100'],
                      [b'movie_1207', b'movie_593', b'movie_1219'],
                      [b'movie_110', b'movie_1408', b'movie_41'],
                      [b'movie_1575', b'movie_2303', b'movie_3730'],
                      [b'movie_588', b'movie_2394', b'movie_364'],
                      [b'movie_303', b'movie_2723', b'movie_292'],
                      [b'movie_414', b'movie_203', b'movie_2249'],
                      [b'movie_2137', b'movie_1405', b'movie_1023'],
                      [b'movie_1031', b'movie_2133', b'movie_2093'],
                      [b'movie_3500', b'movie_2012', b'movie_596'],
                      [b'movie_412', b'movie_2858', b'movie_1193'],
                      [b'movie_1372', b'movie_368', b'movie_2723'],
                      [b'movie_148', b'movie_984', b'movie_2506'],
                      [b'movie_599', b'movie_1197', b'movie_47'],
                      [b'movie_502', b'movie_1499', b'movie_1591'],
                      [b'movie_480', b'movie_2791', b'movie_1544'],
                      [b'movie_2478', b'movie_237', b'movie_413'],
                      [b'movie_2160', b'movie_3793', b'movie_1466'],
                      [b'movie_3820', b'movie_648', b'movie_3863'],
                      [b'movie_1876', b'movie_350', b'movie_2881'],
                      [b'movie_1641', b'movie_3358', b'movie_3253'],
                      [b'movie_2985', b'movie_3033', b'movie_3156'],
                      [b'movie_185', b'movie_1831', b'movie_2719'],
                      [b'movie_32', b'movie_1270', b'movie_1210'],
                      [b'movie_1206', b'movie_1097', b'movie_1270'],
                      [b'movie_2088', b'movie_1381', b'movie_829'],
                      [b'movie_2384', b'movie_708', b'movie_2353'],
                      [b'movie_175', b'movie_3526', b'movie_1962'],
                      [b'movie_1801', b'movie_61', b'movie_436'],
                      [b'movie_2571', b'movie_21', b'movie_1372'],
                      [b'movie_2027', b'movie_2953', b'movie_2092'],
                      [b'movie_1131', b'movie_1296', b'movie_1220'],
                      [b'movie_719', b'movie_1409', b'movie_1880'],
                      [b'movie_1991', b'movie_2717', b'movie_1995'],
                      [b'movie_110', b'movie_223', b'movie_902'],
                      [b'movie_1136', b'movie_912', b'movie_2300'],
                      [b'movie_3680', b'movie_3658', b'movie_3365'],
                      [b'movie_448', b'movie_1704', b'movie_2908'],
                      [b'movie_1617', b'movie_1210', b'movie_353'],
                      [b'movie_2932', b'movie_2131', b'movie_2730'],
                      [b'movie_2769', b'movie_1921', b'movie_1092'],
                      [b'movie_48', b'movie_312', b'movie_294'],
                      [b'movie_2012', b'movie_2011', b'movie_3525'],
                      [b'movie_1049', b'movie_380', b'movie_303'],
                      [b'movie_1459', b'movie_743', b'movie_2252'],
                      [b'movie_3213', b'movie_1223', b'movie_1566'],
                      [b'movie_69', b'movie_2169', b'movie_1457'],
                      [b'movie_3077', b'movie_136', b'movie_3327'],
                      [b'movie_2872', b'movie_1374', b'movie_1200'],
                      [b'movie_1179', b'movie_913', b'movie_2987'],
                      [b'movie_1997', b'movie_3467', b'movie_1233'],
                      [b'movie_2080', b'movie_3037', b'movie_3671'],
                      [b'movie_2871', b'movie_3386', b'movie_1960'],
                      [b'movie_2012', b'movie_2572', b'movie_3525'],
                      [b'movie_3020', b'movie_2167', b'movie_3755'],
                      [b'movie_1136', b'movie_2959', b'movie_2599'],
                      [b'movie_3203', b'movie_2541', b'movie_2369'],
                      [b'movie_1961', b'movie_440', b'movie_3176'],
                      [b'movie_3448', b'movie_3834', b'movie_1721'],
                      [b'movie_34', b'movie_1094', b'movie_2138'],
                      [b'movie_2804', b'movie_1387', b'movie_2203'],
                      [b'movie_1183', b'movie_1946', b'movie_1683'],
                      [b'movie_1283', b'movie_923', b'movie_912'],
                      [b'movie_842', b'movie_2279', b'movie_2367'],
                      [b'movie_2988', b'movie_969', b'movie_1673'],
                      [b'movie_329', b'movie_2393', b'movie_736'],
                      [b'movie_1175', b'movie_29', b'movie_2997'],
                      [b'movie_2881', b'movie_2136', b'movie_2717'],
                      [b'movie_2854', b'movie_1388', b'movie_1097'],
                      [b'movie_2279', b'movie_3919', b'movie_3708'],
                      [b'movie_921', b'movie_3114', b'movie_1916'],
                      [b'movie_2908', b'movie_2355', b'movie_1093'],
                      [b'movie_805', b'movie_3252', b'movie_2490'],
                      [b'movie_2616', b'movie_3', b'movie_3269'],
                      [b'movie_339', b'movie_317', b'movie_586'],
                      [b'movie_1219', b'movie_2571', b'movie_1250'],
                      [b'movie_2550', b'movie_2553', b'movie_2455'],
                      [b'movie_3147', b'movie_2303', b'movie_1945'],
                      [b'movie_1265', b'movie_2599', b'movie_2289'],
                      [b'movie_435', b'movie_2408', b'movie_2470'],
                      [b'movie_1244', b'movie_17', b'movie_866'],
                      [b'movie_2841', b'movie_1517', b'movie_281'],
                      [b'movie_3256', b'movie_2993', b'movie_3633'],
                      [b'movie_2009', b'movie_3032', b'movie_3751'],
                      [b'movie_3831', b'movie_522', b'movie_3556'],
                      [b'movie_2080', b'movie_2078', b'movie_2355'],
                      [b'movie_921', b'movie_3361', b'movie_1292'],
                      [b'movie_3070', b'movie_3771', b'movie_2115'],
                      [b'movie_1296', b'movie_3111', b'movie_2248'],
                      [b'movie_296', b'movie_457', b'movie_1953'],
                      [b'movie_2605', b'movie_253', b'movie_252'],
                      [b'movie_3243', b'movie_2002', b'movie_170'],
                      [b'movie_3016', b'movie_3627', b'movie_3727'],
                      [b'movie_553', b'movie_2877', b'movie_3509'],
                      [b'movie_1687', b'movie_20', b'movie_3438'],
                      [b'movie_1221', b'movie_1214', b'movie_1304'],
                      [b'movie_2929', b'movie_2240', b'movie_3111'],
                      [b'movie_1586', b'movie_1676', b'movie_708'],
                      [b'movie_3536', b'movie_608', b'movie_1213'],
                      [b'movie_3481', b'movie_3515', b'movie_3753'],
                      [b'movie_1242', b'movie_155', b'movie_151'],
                      [b'movie_2301', b'movie_1958', b'movie_2746'],
                      [b'movie_1614', b'movie_505', b'movie_2448'],
                      [b'movie_3809', b'movie_1875', b'movie_252'],
                      [b'movie_1680', b'movie_2966', b'movie_3225'],
                      [b'movie_95', b'movie_2600', b'movie_882'],
                      [b'movie_913', b'movie_919', b'movie_920'],
                      [b'movie_380', b'movie_1372', b'movie_547'],
                      [b'movie_2977', b'movie_419', b'movie_1713'],
                      [b'movie_1959', b'movie_3325', b'movie_3753'],
                      [b'movie_562', b'movie_2885', b'movie_2024'],
                      [b'movie_355', b'movie_460', b'movie_258'],
                      [b'movie_1271', b'movie_249', b'movie_507'],
                      [b'movie_1690', b'movie_2334', b'movie_434'],
                      [b'movie_662', b'movie_628', b'movie_3512'],
                      [b'movie_3669', b'movie_19', b'movie_2392'],
                      [b'movie_1995', b'movie_3692', b'movie_3799'],
                      [b'movie_1064', b'movie_355', b'movie_881'],
                      [b'movie_2732', b'movie_3169', b'movie_1719'],
                      [b'movie_1304', b'movie_3873', b'movie_3462'],
                      [b'movie_2706', b'movie_1485', b'movie_785'],
                      [b'movie_1590', b'movie_1833', b'movie_1591'],
                      [b'movie_161', b'movie_1051', b'movie_1784'],
                      [b'movie_3324', b'movie_1198', b'movie_193'],
                      [b'movie_2359', b'movie_1042', b'movie_3060'],
                      [b'movie_1120', b'movie_1059', b'movie_3476'],
                      [b'movie_1088', b'movie_912', b'movie_1247'],
                      [b'movie_1214', b'movie_3148', b'movie_110'],
                      [b'movie_5', b'movie_786', b'movie_2169'],
                      [b'movie_357', b'movie_1542', b'movie_1907'],
                      [b'movie_2890', b'movie_1639', b'movie_364'],
                      [b'movie_1581', b'movie_1440', b'movie_435'],
                      [b'movie_3175', b'movie_2355', b'movie_356'],
                      [b'movie_1845', b'movie_2457', b'movie_1449'],
                      [b'movie_3863', b'movie_3826', b'movie_3316'],
                      [b'movie_2310', b'movie_2622', b'movie_2013'],
                      [b'movie_2005', b'movie_2085', b'movie_2140'],
                      [b'movie_1092', b'movie_31', b'movie_2694'],

## 创建 model_inputs

In [66]:
def create_model_inputs():
    return {"user_id": tf.keras.layers.Input(name="user_id", shape=(1,), dtype=tf.string),
                "sequence_movie_ids": tf.keras.layers.Input(
                    name="sequence_movie_ids", shape=(sequence_length - 1,), dtype=tf.string
                ),
                "target_movie_id": tf.keras.layers.Input(
                    name="target_movie_id", shape=(1,), dtype=tf.string
                ),
                "sequence_ratings": tf.keras.layers.Input(
                    name="sequence_ratings", shape=(sequence_length - 1,), dtype=tf.float32
                ),
                "sex": tf.keras.layers.Input(name="sex", shape=(1,), dtype=tf.string),
                "age_group": tf.keras.layers.Input(name="age_group", shape=(1,), dtype=tf.string),
                "occupation": tf.keras.layers.Input(name="occupation", shape=(1,), dtype=tf.string),
                # 'sex_genres': tf.keras.layers.Input(name='sex_genres', shape=(1, ), dtype=tf.float16)
            }

## Encode input features

encode_input_features可以这么操作：

* 每个用户特征均使用tf.keras.layer.Embedding进行编码，embedding_dim等于特征个数的平方根取整。

* 电影序列 sequence_movie_ids 中每部电影和目标电影都使用tf.keras.layers.Embedding编码。Embedding_dim是电影数量的平方根取整。

* 将每部电影的embedding与其电影画像Embedding融合起来，并使用非线性激活函数激活，输出有同等大小的张量。

* **将位置embedding和序列中的每个电影Embedding相加，再乘以分级序列中的分级，相当于把使用评分作为权重给电影id加权**。

* 目标电影Embedding与序列影片Embedding进行连接，生成`[batch_size, seq_len, embedding_dim]`的张量。

* 该方法返回两个元素的元组：encoded_transformer_features和encoded_other_features。

In [67]:
def encode_input_features(inputs, include_user_id=True, include_user_features=True,include_movie_features=True):
    encoded_transformer_features = []
    encoded_other_features = []

    other_feature_names = []
    if include_user_id:
        other_feature_names.append("user_id")
    if include_user_features:
        other_feature_names.extend(USER_FEATURES)

    ## 用户画像编码： user features
    for feature_name in other_feature_names:
        # 在tf中将字符串输入转为整数输入
        vocabulary = CATEGORICAL_FEATURES_WITH_VOCABULARY[feature_name]
        idx = tf.keras.layers.experimental.preprocessing.StringLookup(vocabulary=vocabulary, mask_token=None, num_oov_indices=0)(
            inputs[feature_name]
        )
        # 自动计算embedding_dim的维度
        embedding_dims = int(np.sqrt(len(vocabulary)))
        # 上述特征喂给Embedding
        embedding_encoder = tf.keras.layers.Embedding(
            input_dim=len(vocabulary),
            output_dim=embedding_dims,
            trainable=True,
            name=f"{feature_name}_embedding",
        )
        # 将每个特征的Embedding加入到列表中记录下来
        encoded_other_features.append(embedding_encoder(idx))

    ## 所有用户画像的Embedding拼接成一个向量
    if len(encoded_other_features) > 1:
        encoded_other_features = tf.keras.layers.concatenate(encoded_other_features)
    elif len(encoded_other_features) == 1:
        encoded_other_features = encoded_other_features[0]
    else:
        encoded_other_features = None

    ## 创建电影的Embedding
    movie_vocabulary = CATEGORICAL_FEATURES_WITH_VOCABULARY["movie_id"]
    movie_embedding_dims = int(np.sqrt(len(movie_vocabulary)))
    # 标签编码：在tf中将输入 movieid_823, movieid_821, ... 转为数字
    movie_index_lookup = tf.keras.layers.experimental.preprocessing.StringLookup(
        vocabulary=movie_vocabulary,
        mask_token=None,
        num_oov_indices=0,
        name="movie_index_lookup",
    )
    # 降维：使用tf.keras.layers.Embedding把输入特征降维为固定维度
    movie_embedding_encoder = tf.keras.layers.Embedding(
        input_dim=len(movie_vocabulary),
        output_dim=movie_embedding_dims,
        trainable=True,
        name=f"movie_embedding",
    )
    # 所有电影画像的Embedding拼接为一个向量
    genre_vectors = movies[genres].to_numpy()
    movie_genres_lookup = tf.keras.layers.Embedding(
        input_dim=genre_vectors.shape[0],
        output_dim=genre_vectors.shape[1],
        embeddings_initializer=tf.keras.initializers.Constant(genre_vectors),
        trainable=False,
        name="genres_vector",
    )

    # 构建特征工程 性别和电影类型交叉特征
    # gender_genres = genres
    # gender_genres.append('sex_F')
    # gender_genres.append('sex_M')
    
    # gender_genre_vectors = matrix[gender_genres].to_numpy()
    # gender_genres_lookup = tf.keras.layers.Embedding(input_dim=gender_genre_vectors.shape[0], 
    #                                                  output_dim=gender_genre_vectors.shape[1],
    #                                                  embeddings_initializer=tf.keras.initializers.Constant(gender_genre_vectors), 
    #                                                  trainabel=False,
    #                                                  name='gender_genre_vectors')

    # 为电影画像(genres)创建一个简单的神经网络学习权重，因为genres embedding的权重不更新(trainabel=False)，所以单独设置神经网络学习权重
    movie_embedding_processor = tf.keras.layers.Dense(
        units=movie_embedding_dims,
        activation="relu",
        name="process_movie_embedding_with_genres",
    )

    ## 定义函数对给定的movie_id进行编码
    def encode_movie(movie_id):
        # 标签编码：在tf中将字符串转为整数
        movie_idx = movie_index_lookup(movie_id)
        # 用Embedding向量表示一个movie_id
        movie_embedding = movie_embedding_encoder(movie_idx)
        encoded_movie = movie_embedding
        if include_movie_features:
            movie_genres_vector = movie_genres_lookup(movie_idx)
            # 电影画像 = movie_id embedding + genres embedding
            encoded_movie = movie_embedding_processor(
                tf.keras.layers.concatenate([movie_embedding, movie_genres_vector])
            )
        return encoded_movie

    ## 编码 target_movie_id
    target_movie_id = inputs["target_movie_id"]
    encoded_target_movie = encode_movie(target_movie_id)

    ## 编码用户观看电影序列 sequence movie_ids.
    sequence_movies_ids = inputs["sequence_movie_ids"]
    encoded_sequence_movies = encode_movie(sequence_movies_ids)
    # 创建序列的位置编码 positional embedding
    position_embedding_encoder = tf.keras.layers.Embedding(
        input_dim=sequence_length,
        output_dim=movie_embedding_dims,
        trainable=True,
        name="position_embedding",
    )

    positions = tf.range(start=0, limit=sequence_length - 1, delta=1)
    encodded_positions = position_embedding_encoder(positions)
    # 找到电影对应的评分序列（sequence ratings）后，跟电影embedding融合者融合
    sequence_ratings = tf.expand_dims(inputs["sequence_ratings"], -1)
    # 给 movie encodings 增加 Positional Embedding，
    # 之后再乘以用户对这些电影的打分
    encoded_sequence_movies_with_poistion_and_rating = tf.keras.layers.Multiply()(
        [(encoded_sequence_movies + encodded_positions), sequence_ratings]
    )

    # 输入Transformer的embedding进行拼接
    for encoded_movie in tf.unstack(encoded_sequence_movies_with_poistion_and_rating, axis=1):
        encoded_transformer_features.append(tf.expand_dims(encoded_movie, 1))
    encoded_transformer_features.append(encoded_target_movie)

    encoded_transformer_features = tf.keras.layers.concatenate(encoded_transformer_features, axis=1)

    return encoded_transformer_features, encoded_other_features
    
# 未来可升级的地方
# 修改为类别特征和连续特征 类别特征喂给FM，dense特征喂给DNN

## Create a BST model

原始例子中other_features没有喂给Transformer，只喂了sequence

【未完成】所有特征都喂给Transformer

【未完成】other feature 需要喂给FM做特征交叉

In [68]:
include_user_id = False
include_user_features = False
include_movie_features = False

hidden_units = [256, 128] # 使用3层全连接层效果下降，应该是网络层数导致模型发生退化问题
dropout_rate =  0.1
num_heads = 3


def create_model():
    inputs = create_model_inputs()
    transformer_features, other_features = encode_input_features(
        inputs, include_user_id, include_user_features, include_movie_features
    )

    # 输出数据进行归一化
    # transform_features = tf.keras.layers.LayerNormalization()(transformer_features)

    # 搭建 Multi-head Attention 层
    attention_output = tf.keras.layers.MultiHeadAttention(
        num_heads=num_heads, key_dim=transformer_features.shape[2], dropout=dropout_rate
    )(transformer_features, transformer_features)

    # Transformer block.
    attention_output = tf.keras.layers.Dropout(dropout_rate)(attention_output)
    # 残差连接
    x1 = tf.keras.layers.Add()([transformer_features, attention_output])
    # 可将layerNormalization 向前调整到输入层
    x1 = tf.keras.layers.LayerNormalization()(x1)
    x2 = tf.keras.layers.LeakyReLU()(x1)
    x2 = tf.keras.layers.Dense(units=x2.shape[-1])(x2)
    x2 = tf.keras.layers.Dropout(dropout_rate)(x2)
    # Add & Norm 残差连接 & 层归一化
    transformer_features = tf.keras.layers.Add()([x1, x2])
    transformer_features = tf.keras.layers.LayerNormalization()(transformer_features)
    features = tf.keras.layers.Flatten()(transformer_features) #(None, 248)

    # 包含其他特征
    # if other_features is not None:
    #     features = tf.keras.layers.concatenate(
    #         [features, tf.keras.layers.Reshape([other_features.shape[-1]])(other_features)]
    #     )

        # concated_embeds_value = tf.keras.layers.Reshape([other_features.shape[-1]])(other_features)
        # square_of_sum = tf.square(tf.reduce_sum(concated_embeds_value, axis=1), keepdims=True)
        # sum_of_square = tf.reduce_sum(tf.pow(concated_embeds_value, 2), axis=1, keepdims=True)  # concated_embeds_value * concated_embeds_value
        # other_features = 0.5 * (square_of_sum - sum_of_square)
        # features = tf.concat([features, other_features], axis=1)

    # Fully-connected layers.
    features_ori = features
    for num_units in hidden_units:
        features = tf.keras.layers.Dense(num_units)(features)
        features = tf.keras.layers.BatchNormalization()(features)
        features = tf.keras.layers.LeakyReLU()(features)
        features = tf.keras.layers.Dropout(dropout_rate)(features)
    
    # outputs = dnn_n_resnet(features)
    # 残差连接
    # features_ori = tf.keras.layers.Dense(units=hidden_units[-1], activation=None, trainable=False)(features_ori)
    # features = tf.concat([features, features_ori], axis=-1)
    # features = features + features_ori
    outputs = tf.keras.layers.Dense(units=1)(features)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    return model

model = create_model()

In [105]:
include_user_id = False
include_user_features = False
include_movie_features = False

hidden_units = [256, 128, 64] # 使用3层全连接层效果下降，应该是网络层数导致模型发生退化问题
dropout_rate =  0.3
num_heads = 3


def create_model():
    inputs = create_model_inputs()
    transformer_features, other_features = encode_input_features(
        inputs, include_user_id, include_user_features, include_movie_features
    )

    # transformer_features = tf.keras.layers.concatenate([transform_features, other_features])
    # 输出数据进行归一化
    transform_features = tf.keras.layers.LayerNormalization()(transformer_features)

    # 搭建 Multi-head Attention 层
    attention_output = tf.keras.layers.MultiHeadAttention(
        num_heads=num_heads, key_dim=transformer_features.shape[2], dropout=dropout_rate
    )(transformer_features, transformer_features)

    # Transformer block.
    attention_output = tf.keras.layers.Dropout(dropout_rate)(attention_output)
    # 残差连接
    x1 = tf.keras.layers.Add()([transformer_features, attention_output])
    # 可将layerNormalization 向前调整到输入层
    x1 = tf.keras.layers.LayerNormalization()(x1)
    x2 = tf.keras.layers.LeakyReLU()(x1)
    x2 = tf.keras.layers.Dense(units=x2.shape[-1])(x2)
    x2 = tf.keras.layers.Dropout(dropout_rate)(x2)
    # Add & Norm 残差连接 & 层归一化
    transformer_features = tf.keras.layers.Add()([x1, x2])
    transformer_features = tf.keras.layers.LayerNormalization()(transformer_features)
    features = tf.keras.layers.Flatten()(transformer_features) #(None, 248)

    # 包含其他特征
    # if other_features is not None:
    #     features = tf.keras.layers.concatenate(
    #         [features, tf.keras.layers.Reshape([other_features.shape[-1]])(other_features)]
    #     )

        # concated_embeds_value = tf.keras.layers.Reshape([other_features.shape[-1]])(other_features)
        # square_of_sum = tf.square(tf.reduce_sum(concated_embeds_value, axis=1), keepdims=True)
        # sum_of_square = tf.reduce_sum(tf.pow(concated_embeds_value, 2), axis=1, keepdims=True)  # concated_embeds_value * concated_embeds_value
        # other_features = 0.5 * (square_of_sum - sum_of_square)
        # features = tf.concat([features, other_features], axis=1)

    # Fully-connected layers.
    features_ori = features
    for num_units in hidden_units:
        features = tf.keras.layers.Dense(num_units)(features)
        features = tf.keras.layers.BatchNormalization()(features)
        features = tf.keras.layers.LeakyReLU()(features)
        features = tf.keras.layers.Dropout(dropout_rate)(features)
    
    # outputs = dnn_n_resnet(features)
    # 残差连接
    # features_ori = tf.keras.layers.Dense(units=hidden_units[-1], activation=None, trainable=False)(features_ori)
    # features = tf.concat([features, features_ori], axis=-1)
    # features = features + features_ori
    outputs = tf.keras.layers.Dense(units=1)(features)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    return model

model = create_model()

## Run training and evaluation experiment

In [106]:
model.summary()

Model: "model_6"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
sequence_movie_ids (InputLayer) [(None, 3)]          0
__________________________________________________________________________________________________
movie_index_lookup (StringLooku multiple             0           target_movie_id[0][0]
                                                                 sequence_movie_ids[0][0]
__________________________________________________________________________________________________
movie_embedding (Embedding)     multiple             240746      movie_index_lookup[0][0]
                                                                 movie_index_lookup[1][0]
__________________________________________________________________________________________________
sequence_ratings (InputLayer)   [(None, 3)]          0
__________________________________________________________________________________________________
tf.__operators__.add_7 (TFOpLam (None, 3, 62)        0           movie_embedding[1][0]
__________________________________________________________________________________________________
tf.expand_dims_28 (TFOpLambda)  (None, 3, 1)         0           sequence_ratings[0][0]
__________________________________________________________________________________________________
multiply_7 (Multiply)           (None, 3, 62)        0           tf.__operators__.add_7[0][0]
                                                                 tf.expand_dims_28[0][0]
__________________________________________________________________________________________________
target_movie_id (InputLayer)    [(None, 1)]          0
__________________________________________________________________________________________________
tf.unstack_7 (TFOpLambda)       [(None, 62), (None,  0           multiply_7[0][0]
__________________________________________________________________________________________________
tf.expand_dims_29 (TFOpLambda)  (None, 1, 62)        0           tf.unstack_7[0][0]
__________________________________________________________________________________________________
tf.expand_dims_30 (TFOpLambda)  (None, 1, 62)        0           tf.unstack_7[0][1]
__________________________________________________________________________________________________
tf.expand_dims_31 (TFOpLambda)  (None, 1, 62)        0           tf.unstack_7[0][2]
__________________________________________________________________________________________________
concatenate_7 (Concatenate)     (None, 4, 62)        0           tf.expand_dims_29[0][0]
                                                                 tf.expand_dims_30[0][0]
                                                                 tf.expand_dims_31[0][0]
                                                                 movie_embedding[0][0]
__________________________________________________________________________________________________
multi_head_attention_6 (MultiHe (None, 4, 62)        46748       concatenate_7[0][0]
                                                                 concatenate_7[0][0]
__________________________________________________________________________________________________
dropout_25 (Dropout)            (None, 4, 62)        0           multi_head_attention_6[0][0]
__________________________________________________________________________________________________
add_12 (Add)                    (None, 4, 62)        0           concatenate_7[0][0]
                                                                 dropout_25[0][0]
__________________________________________________________________________________________________
layer_normalization_16 (LayerNo (None, 4, 62)        124         add_12[0][0]
__________________________________________________________________________________________________
leaky_re_lu_19 (LeakyReLU)      (None, 4, 62)        0           layer_normalization_16[0][0]
__________________________________________________________________________________________________
dense_25 (Dense)                (None, 4, 62)        3906        leaky_re_lu_19[0][0]
__________________________________________________________________________________________________
dropout_26 (Dropout)            (None, 4, 62)        0           dense_25[0][0]
__________________________________________________________________________________________________
add_13 (Add)                    (None, 4, 62)        0           layer_normalization_16[0][0]
                                                                 dropout_26[0][0]
__________________________________________________________________________________________________
layer_normalization_17 (LayerNo (None, 4, 62)        124         add_13[0][0]
__________________________________________________________________________________________________
flatten_6 (Flatten)             (None, 248)          0           layer_normalization_17[0][0]
__________________________________________________________________________________________________
dense_26 (Dense)                (None, 300)          74700       flatten_6[0][0]
__________________________________________________________________________________________________
batch_normalization_13 (BatchNo (None, 300)          1200        dense_26[0][0]
__________________________________________________________________________________________________
leaky_re_lu_20 (LeakyReLU)      (None, 300)          0           batch_normalization_13[0][0]
__________________________________________________________________________________________________
dropout_27 (Dropout)            (None, 300)          0           leaky_re_lu_20[0][0]
__________________________________________________________________________________________________
dense_27 (Dense)                (None, 200)          60200       dropout_27[0][0]
__________________________________________________________________________________________________
batch_normalization_14 (BatchNo (None, 200)          800         dense_27[0][0]
__________________________________________________________________________________________________
leaky_re_lu_21 (LeakyReLU)      (None, 200)          0           batch_normalization_14[0][0]
__________________________________________________________________________________________________
dropout_28 (Dropout)            (None, 200)          0           leaky_re_lu_21[0][0]
__________________________________________________________________________________________________
dense_28 (Dense)                (None, 100)          20100       dropout_28[0][0]
__________________________________________________________________________________________________
batch_normalization_15 (BatchNo (None, 100)          400         dense_28[0][0]
__________________________________________________________________________________________________
leaky_re_lu_22 (LeakyReLU)      (None, 100)          0           batch_normalization_15[0][0]
__________________________________________________________________________________________________
dropout_29 (Dropout)            (None, 100)          0           leaky_re_lu_22[0][0]
__________________________________________________________________________________________________
age_group (InputLayer)          [(None, 1)]          0
__________________________________________________________________________________________________
occupation (InputLayer)         [(None, 1)]          0
__________________________________________________________________________________________________
sex (InputLayer)                [(None, 1)]          0
__________________________________________________________________________________________________
user_id (InputLayer)            [(None, 1)]          0
__________________________________________________________________________________________________
dense_29 (Dense)                (None, 1)            101         dropout_29[0][0]
==================================================================================================
Total params: 449,149
Trainable params: 447,949
Non-trainable params: 1,200
__________________________________________________________________________________________________

In [107]:
%%time
# Compile the model.
model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.MeanSquaredError(),
    metrics=[tf.keras.metrics.MeanAbsoluteError()],
)

# Read the training data.
train_dataset = get_dataset_from_csv("train_data.csv", shuffle=True, batch_size=512)
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_f1', patience=3, restore_best_weights=True)

# Fit the model with the training data.
model.fit(train_dataset, epochs=5,
        #   callbacks=[early_stopping],  # checkpoint

          )

# Read the test data.
test_dataset = get_dataset_from_csv("test_data.csv", batch_size=265) # 512

# Evaluate the model on the test data.
_, rmse = model.evaluate(test_dataset, verbose=0)
print(f"Test MAE: {round(rmse, 3)}")
# ===========================Test==============================
# print('test AUC: %f' % model.evaluate(test_X, test_y, batch_size=batch_size)[1])

Epoch 1/5
829/829 [==============================] - 14s 15ms/step - loss: 4.0266 - mean_absolute_error: 1.5569
Epoch 2/5
829/829 [==============================] - 12s 15ms/step - loss: 1.3136 - mean_absolute_error: 0.9152
Epoch 3/5
829/829 [==============================] - 12s 15ms/step - loss: 1.1108 - mean_absolute_error: 0.8433
Epoch 4/5
829/829 [==============================] - 12s 14ms/step - loss: 1.0304 - mean_absolute_error: 0.8106
Epoch 5/5
829/829 [==============================] - 12s 15ms/step - loss: 0.9824 - mean_absolute_error: 0.7920
Test MAE: 0.757
CPU times: user 1min 25s, sys: 13.7 s, total: 1min 39s
Wall time: 1min 4s

In [81]:
ratings

           user_id    movie_id  rating  unix_timestamp
0           user_1  movie_1193     5.0       978300760
1           user_1   movie_661     3.0       978302109
2           user_1   movie_914     3.0       978301968
3           user_1  movie_3408     4.0       978300275
4           user_1  movie_2355     5.0       978824291
...            ...         ...     ...             ...
1000204  user_6040  movie_1091     1.0       956716541
1000205  user_6040  movie_1094     5.0       956704887
1000206  user_6040   movie_562     5.0       956704746
1000207  user_6040  movie_1096     4.0       956715648
1000208  user_6040  movie_1097     4.0       956715569

[1000209 rows x 4 columns]